version: '3.4'

services:
  fastapi-template:
    container_name: fastapi-template
    build: .
    image: fastapi-template:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000

  database:
    image: postgres:11
    container_name: database
    restart: always
    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
      - database_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    network_mode: host
    command: redis-server --requirepass password
    ports:
      - 6379:6379

volumes:
  database_data:
    name: database_data