name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Login to Github Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.pkg.github.com/darkbordermantemplate/fastapi-redis-sqlalchemy/dev
